version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/express-app
permissions:
  - object: /home/ubuntu/express-app
    owner: ubuntu
    group: ubuntu
hook:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 900
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 900
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 900
      runas: ubuntu
    